<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <UseWPF>false</UseWPF>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <StartupObject>Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Models\*.cs" LinkBase="Models" />
    <Compile Include="..\Services\*.cs" LinkBase="Services" />
  </ItemGroup>

</Project>
